### ISSUE TITLE
should we update the auto-generated participants file for QPN?

### ISSUE THREAD

**Issue by surchs** [neurodatascience/mr_proc#31]
In the QPN BIDS dataset (`bic:/data/pd/qpn/bids`) are 163 subject directories and a `participants.tsv` file that was auto-generated by heudiconv (I think). This `participants.tsv` file contains 163 subject entries, all of which are "control" subjects - as far as I know, because of an issue related to heudiconv. There is also a demographics directory for QPN (`bic:/data/pd/qpn/clinical/demographics`), that contains a `participants.csv` file with 295 subjects with more reasonable looking diagnostic status ("Control" or "Parkinson"). However, the subjects in this file don't have a BIDS conform `participant_id`, e.g.: `MNI0056` instead of `sub-MNI0056` and because we only have 163 subject directories in the BIDS directory, only some of these subjects should probably be included in the accompanying `participants.tsv` file.

All that to say: how should we update the QPN BIDS dataset so that the `participants.tsv` file contains correct data? 
And secondly: where should whatever we chose to do be documented, so that we could do it again if we lost the data?

**Comment by nikhil153** [comment]
@surchs All good questions! Following is what I had in mind, of which the implementation+documentation is lagging atm. 
1. Organization: `demographics/participants.csv` is the global participants manifest for all modalities (i.e. imaging + tabular). The demographic info in this file is the validated ground-truth. All other lists of participants are subsets of this depending on the data availability. Thus the `/bids/participants.tsv` would be an imaging subset of participants. All other columns in this file should be ignored. 
2. Naming conflicts between participant lists: Yes, I need to fix that! 
3. So far I am documenting all the steps in README files under mr_proc branches. Happy to try other alternatives.

**Comment by surchs** [comment]
Thanks for the explanation! I did play a bit with the matching and it seems that the main difference between the `participant_ids` of both files is that the BIDS ids have an additional suffix like so `...D725903` that the demographic IDs do not have. 

so `sub-PD01369D713546` (BIDS) -> `PD01369` (Demographic). 

I managed to map 143 of the BIDS subjects into the demo list, but there are 20 where I can't find a match. That is, these IDs seem to exist only in the BIDS participant.tsv file, not the demographic one.

<details>
  <summary>BIDS subjects not in Demographics</summary>
```
sub-PD00435D874573
sub-PD00975D638945
sub-PD01297D456457
sub-PD01442D145287
sub-PD01526D307101
sub-PD01550D280506
sub-PD01577D642390
sub-PD01603D353288
sub-PD01722D171254
sub-PD01751D106182
sub-PD00016D880738
sub-PD00032D891772
sub-PD00950D894443
sub-PD00959D756738
sub-PD01448D152817
sub-MNI0200D646765
sub-MNI0136D587352
sub-PD00911D620262
sub-PD01677D994657
sub-PD00122D725903
```
</details>

So my (new) two questions are:

1. Do you want me to use the mappings I have found (BIDS -> demo) and if so, where should I put them?
2. Any idea why the above subjects seem to exist in BIDS, but not in demo?

**Comment by nikhil153** [comment]
1. Do you want me to use the mappings I have found (BIDS -> demo) and if so, where should I put them?
So let's not create additional mappings. I will update the `demographics/participants.csv` to match BIDS format of naming. The reason for additional naming suffix comes from earlier days when there was no single list of subjects + visits. Therefore we added this LORIS generated ID to ensure unique subject IDs. 
2. Any idea why the above subjects seem to exist in BIDS, but not in demo?
This again goes back to earlier days when there was no single manifest of subjects. We had more dicoms than what qpn.loris showed. This should be fixed by now, and I will validate that when I update the `demographics/participants.csv`. But as a rule of thumb `demographics/participants.csv` is the validated ground-truth if you see additional subjects anywhere, you should ignore them until they are added to `demographics/participants.csv` by data managers.

**Comment by surchs** [comment]
OK, I'll wait for the updated `demographics/participants.csv` before I continue. Let me know if I can help with that.

**Comment by nikhil153** [comment]
Okay I just added mapping from study-generated participant_id to bids_id in the global participants.csv. Let me know if there are any other issues!

**Comment by surchs** [comment]
Thanks @nikhil153, I can annotate the `participants.csv` file you made. As we have discussed, there are some subjects in the BIDS directory that don't exist in the demographic information. For now, we will not add these subjects to the graph.

See also: https://github.com/neurobagel/bagelbids/issues/9

**Comment by surchs** [comment]
I have a related question (maybe for a new issue ?):
Today you mentioned that you'd like us to keep data for subjects with demographic information but without imaging. How would this work here, where some subjects

- have demo + imaging; have a `bids_id` in addition to their `participant_id` -> keep
- have imaging only, no demo -> exclude
- have demo only, no imaging; have **no** `bids_id` but only the `participant_id` -> also keep

Would you want to create `bids_id` for the "demo only" subjects even though they don't have any BIDS data? Basically: how do we deal with the demo-only subjects without having to handle two separate participant_id schemes?

**Comment by nikhil153** [comment]
I agree with your exclusion criteria. 
What exactly is the issue of handling two separate participant_id schemes? Since we cannot force recruitment or BIDS standard to converge to single naming schemes, that would be true regardless of the exclusion criteria, right? To me the `participant_id` is the `primary id` for a given subject. Could any other ids, such as `bids_id`, generated downstream be just the property of a "subject node" in your graph?

**Comment by surchs** [comment]
It just makes our life quite a bit harder if in addition to merging imaging and demographic metadata, we also have to resolve mappings between two separate subject_id naming schemes - with all of the possible errors that can happen. So the question for me is where (and when) this additional complexity is going to be resolved. 

If this is a relatively uncommon issue, or at least one that doesn't take the same form in many cases, it should probably part of some acceptable "preprocessing" of data before you can use our tools. 

If instead this is a very common problem that affects many of the datasets we'll want to handle in the same way, then it should probably be handled on the side of our tools.

**Comment by nikhil153** [comment]
Now replaced by bagel.csv
