### ISSUE TITLE
directory structure for tractoflow temporary ?

### ISSUE THREAD

**Issue by jbpoline** [neurodatascience/mr_proc#41]
Hi ! maybe this is just temporary but I found 
/data/pd/qpn/tractoflow/derivatives/tractoflow/v2.2.1/output/tractoflow/*...
is there a reason why this is not in /data/pd/qpn/derivatives? maybe just temporary ?

**Comment by bcmcpher** [comment]
Yeah, I initially created it there because of a permissions issues and I didn't want to make a mess in a working output directory as I was getting started with the mr_proc.

The `../derivatives/v2.2.1/tractoflow` can be moved there now if you'd like. The code in my pending PR accommodates different output paths.

**Comment by jbpoline** [comment]
:+1:

**Comment by bcmcpher** [comment]
Files are relocated into the refactored structure, folder removed.
